### ISSUE TITLE
Unable to install apps: 413 (Request Entity Too Large)

### ISSUE THREAD

**Issue by Awnage** [baosystems/dhis2-centos#2]
When trying to add an app I am getting this message:
<img width="633" alt="screen shot 2018-05-02 at 11 34 14 pm" src="https://user-images.githubusercontent.com/368749/39559122-e26348e6-4e61-11e8-969c-fed7b89e87cc.png">

Might want to add 
`client_max_body_size 100MB;`
to the server section of `/etc/nginx/nginx.conf`

**Comment by alanivey** [comment]
Potentially solved in #3.
