### ISSUE TITLE
Re-provisioning fails because postgis extension already exists

### ISSUE THREAD

**Issue by davidhuser** [baosystems/dhis2-centos#6]
If `vagrant up --provision` is called more than once, the re-provisioning fails because postgis is already installed.

In [main.yml line 263](https://github.com/baosystems/dhis2-centos/blob/master/main.yml#L263
) a `IF NOT EXISTS` could be added:
` --command="CREATE EXTENSION IF NOT EXISTS postgis WITH SCHEMA postgis;"`

A possible use case is provisioning with another DHIS2 version as described in the README.

**Comment by davidhuser** [comment]
@alanthing what do you think?

**Comment by alanivey** [comment]
Thanks @davidhuser for the bug report. [The previous section checks to see if the postgis extension is present in the postgis schema](https://github.com/baosystems/dhis2-centos/blob/6467fe3/main.yml#L242-L256). The regex to check was `^postgis\|[0-9.]+*\|postgis\|`. This works when PostGIS was something like `2.4.1`, but the version installed by the `postgis2_10` package was `2.5.0beta2` as of this writing. The regex is only checking for numbers and periods and therefore failed. 

The commit referenced above will account for PostgreSQL module versions that have text. While your suggestion of adding `IF NOT EXISTS` to the SQL would have prevented the Ansible playbook from completely failing, it doesn't reveal the full context back to the Ansible playbook for use in other commands. In other words, the section that is getting updated effectively does the same thing, and we can use the result from the shell command for future processing.
